### ISSUE TITLE
update component for Qt 5.14.2

### ISSUE THREAD

**Issue by nguoithichkhampha** [Skycoder42/QtService#10]
@Skycoder42 , pls update your repository to available in Qt 5.14.2.
Thanks

**Comment by datased2019** [comment]
@nguoithichkhampha Did you build it by yourself for Qt 5.14.2?

**Comment by nguoithichkhampha** [comment]
yes @datased2019

**Comment by datased2019** [comment]
> 

Could you pls share the MSVC version because I am still facing some problem when compile it using VS. Thx.

**Comment by nguoithichkhampha** [comment]
@datased2019 , actually we are using the version build with Qt 5.15 and we also have some modifications to fix the issue which we found

**Comment by datased2019** [comment]
@nguoithichkhampha  OK. Got it. Thx anyway.
