### ISSUE TITLE
Release date of QtService for Qt 5.15.0

### ISSUE THREAD

**Issue by nguoithichkhampha** [Skycoder42/QtService#16]
I see you have a pre-release version support for Qt 5.15.0. Can you share your plan of official release for Qt 5.15.0 ?

**Comment by Skycoder42** [comment]
The published binaries are already usable as is - only the installer uploads are still missing, but the will follow soon. I have marked the release as production ready.

**Comment by nguoithichkhampha** [comment]
thanks @Skycoder42 , hope installer will go live soon

**Comment by Skycoder42** [comment]
It's online now
