### ISSUE TITLE
qt.service.service: No backend found for the name "standard"

### ISSUE THREAD

**Issue by icemanpro** [Skycoder42/QtService#22]
build in QT 5.15.2+VS2019 Win32.when app is running,the app show this.

mingw81_32 Debug build app and no show it ,but Release build app still show it.

**Comment by aidinmc** [comment]
I wrote my service with QtService and work fine when run from QtCreator, but on the server get this error
what should I do? what is backend exactly? how install and run service? 
I search the whole Documentation but did not find anything

**Comment by aidinmc** [comment]
Finally, I find the solution:

We must copy the `path/to/qt/gcc_64/plugins/servicebackends` directory next to executable

**Comment by Skycoder42** [comment]
Hi, I was just about to suggest that. I am glad you found out yourself
