### ISSUE TITLE
Learn QTService from Scratch

### ISSUE THREAD

**Issue by Dheeraj-Github** [Skycoder42/QtService#31]
Hii!! How Can I make services for windows using QT C++ programming, I want to learn qtservice from the scratch, Can anyone helpme in this ?  Share me a reference or documentary where I learn QT service step by step.

**Comment by Skycoder42** [comment]
https://skycoder42.github.io/QtService/

**Comment by Dheeraj-Github** [comment]
when I run this project in QT 6 there are so many errors are come.
