### ISSUE TITLE
QTService with QProcess

### ISSUE THREAD

**Issue by datased2019** [Skycoder42/QtService#6]
Hi. I am trying touse QTService as my service solution and have to call other python script during service running. I have tested it and works well on normal mode without --backend windows. But when I install it as a windows services, the QTService main process is running well but python script didn't work any more. Any comments on that? 
Thx a lot.

**Comment by Skycoder42** [comment]
Hi. This is propably a limitation of windows services. The following [StackOverflow Post](https://stackoverflow.com/q/5307968/3767076) sheds some light on the issue (even though it's a question for C#, the solutions are the same).

You can try out a few of those ideas by implementing them as native code in your application. Sadly, this is definitely out of scope for this project, but if you need any help, feel free to ask. 

If you manage to solve the problem, I would be happy if you post your resolution here so other users can find it.

**Comment by Skycoder42** [comment]
Another idea would be do embedd your python code into your service application. See https://docs.python.org/3/extending/embedding.html for more details. I do not now if this works, but it might be a workaround for your specific problem.

**Comment by windymindy** [comment]
@datased2019 Hi. Have you check %PATH% and current working directory?

**Comment by datased2019** [comment]
After tried it serveral times, I just find out normal console python works fine in QProcess, so anyone could run batch command easily under QTService. But pls don't try anything related to graphic card or others under Session0 which backgroud service runs. And I want my QTService run batch rendering and it fails without any expection.
