### ISSUE TITLE
qmake Cannot find feature qdep

### ISSUE THREAD

**Issue by EndrII** [Skycoder42/QtService#7]
I need to build this service.
but there are problems at the qmake stage

``` bash
andrei@HP-Laptop-15:~/gitHub/QtService$ ~/Qt/5.13.2/gcc_64/bin/qmake -r 
Reading /home/andrei/gitHub/QtService/src/src.pro
 Reading /home/andrei/gitHub/QtService/src/service/service.pro
Project MESSAGE: perl -w /home/andrei/Qt/5.13.2/gcc_64/bin/syncqt.pl -module QtService -version 2.0.2 -outdir /home/andrei/gitHub/QtService -builddir /home/andrei/gitHub/QtService /home/andrei/gitHub/QtService
<srcbase> = /home/andrei/gitHub/QtService 
<bldbase> = /home/andrei/gitHub/QtService 
<outbase> = /home/andrei/gitHub/QtService 
/home/andrei/gitHub/QtService/src/service/service.pro:45: Cannot find feature qdep
Project ERROR: Failed to load qdep feature! Run 'qdep prfgen --qmake /home/andrei/Qt/5.13.2/gcc_64/bin/qmake' to create it.
```

I need detailed instructions or a way to build this service from source and without installing additional components.

P.S.
Thank you for your project, a very interesting job.)

**Comment by Skycoder42** [comment]
As you can see in the error output, you need to run `qdep prfgen --qmake /home/andrei/Qt/5.13.2/gcc_64/bin/qmake` to make it work. The [README](https://github.com/Skycoder42/QtService#downloadinstallation) clearly states, you have to 

> I. Install and prepare [qdep](https://github.com/Skycoder42/qdep#installation)

to be able to build the library. It is a required tool that pulls in additional dependencies at compile time. If you want to get all sources beforehand, that is also possible, but you still need qdep both to get the sources, as well as to pull them in at compile time. Check that project for more details...

**Comment by EndrII** [comment]
@Skycoder42  Thanks, I will try to understand with qdep.

**Comment by Skycoder42** [comment]
If you have any further questions on how to get it to work, feel free to ask
